name: varitex
channels:
  - pytorch3d
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _pytorch_select=0.2=gpu_0
  - absl-py=0.11.0=py38h578d9bd_0
  - aiohttp=3.7.3=py38h25fe258_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - async-timeout=3.0.1=py_1000
  - attrs=20.3.0=pyhd3deb0d_0
  - bcrypt=3.2.0=py38h1e0a361_1
  - blas=1.0=mkl
  - blinker=1.4=py_1
  - brotlipy=0.7.0=py38h8df0ef7_1001
  - c-ares=1.17.1=h36c2ea0_0
  - ca-certificates=2020.12.5=ha878542_0
  - cachetools=4.1.1=py_0
  - certifi=2020.12.5=py38h578d9bd_1
  - cffi=1.14.4=py38h261ae71_0
  - chardet=3.0.4=py38h924ce5b_1008
  - click=7.1.2=pyh9f0ad1d_0
  - cryptography=3.3.1=py38h3c74f83_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - cycler=0.10.0=py38_0
  - dbus=1.13.18=hb2f20db_0
  - expat=2.2.10=he6710b0_2
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.10.4=h5ab3b9f_0
  - fs=2.4.11=py38h32f6830_2
  - fs.sshfs=1.0.0=pyhd8ed1ab_1
  - fsspec=0.8.5=pyhd8ed1ab_0
  - future=0.18.2=py38h578d9bd_2
  - fvcore=0.1.2.post20201218=pyhd8ed1ab_0
  - glib=2.66.1=h92f7085_0
  - google-auth=1.24.0=pyhd3deb0d_0
  - google-auth-oauthlib=0.4.1=py_2
  - grpcio=1.33.2=py38heead2fc_2
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb31296c_0
  - h5py=2.10.0=py38hd6299e0_1
  - hdf5=1.10.6=hb1b8bf9_0
  - icu=58.2=he6710b0_3
  - idna=2.10=pyh9f0ad1d_0
  - imageio=2.9.0=py_0
  - importlib-metadata=3.3.0=py38h578d9bd_3
  - intel-openmp=2020.2=254
  - joblib=1.0.0=pyhd3eb1b0_0
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.3.0=py38h2531618_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.13.0.1=hd408876_0
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libuv=1.40.0=h7b6447c_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - lz4-c=1.9.2=heb0550a_3
  - markdown=3.3.3=pyh9f0ad1d_0
  - matplotlib=3.3.2=h06a4308_0
  - matplotlib-base=3.3.2=py38h817c723_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py38he904b0f_0
  - mkl_fft=1.2.0=py38h23d657b_0
  - mkl_random=1.1.1=py38h0573a6f_0
  - multidict=5.1.0=py38h27cfd23_2
  - ncurses=6.2=he6710b0_1
  - ninja=1.10.2=py38hff7bd54_0
  - numpy=1.19.2=py38h54aff64_0
  - numpy-base=1.19.2=py38hfa32c7d_0
  - oauthlib=3.0.1=py_0
  - olefile=0.46=py_0
  - openssl=1.1.1j=h27cfd23_0
  - packaging=20.8=pyhd3deb0d_0
  - paramiko=2.7.2=pyh9f0ad1d_0
  - pcre=8.44=he6710b0_0
  - pillow=8.0.1=py38he98fc37_0
  - pip=20.3.3=py38h06a4308_0
  - portalocker=1.7.0=py38h32f6830_1
  - property-cached=1.6.4=py_0
  - protobuf=3.13.0.1=py38he6710b0_1
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=py_2
  - pyjwt=2.0.0=pyhd8ed1ab_0
  - pynacl=1.4.0=py38h1e0a361_2
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py38h05f1152_4
  - pysocks=1.7.1=py38h924ce5b_2
  - python=3.8.5=h7579374_1
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytorch=1.7.0=py3.8_cuda10.2.89_cudnn7.6.5_0
  - pytorch3d=0.3.0=py38_cu102_pyt170
  - pytz=2021.1=pyhd8ed1ab_0
  - pyyaml=5.3.1=py38h8df0ef7_1
  - qt=5.9.7=h5867ecd_1
  - readline=8.0=h7b6447c_0
  - requests=2.25.1=pyhd3deb0d_0
  - requests-oauthlib=1.3.0=pyh9f0ad1d_0
  - rsa=4.6=pyh9f0ad1d_0
  - setuptools=51.0.0=py38h06a4308_2
  - sip=4.19.13=py38he6710b0_0
  - six=1.15.0=py38h06a4308_0
  - sqlite=3.33.0=h62c20be_0
  - tabulate=0.8.7=pyh9f0ad1d_0
  - tensorboard=2.4.0=pyhd8ed1ab_0
  - tensorboard-plugin-wit=1.7.0=pyh9f0ad1d_0
  - termcolor=1.1.0=py_2
  - tk=8.6.10=hbc83047_0
  - torchvision=0.8.1=py38_cu102
  - tornado=6.1=py38h27cfd23_0
  - tqdm=4.55.1=pyhd8ed1ab_0
  - typing-extensions=3.7.4.3=0
  - typing_extensions=3.7.4.3=py_0
  - urllib3=1.26.2=pyhd8ed1ab_0
  - werkzeug=1.0.1=pyh9f0ad1d_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - yacs=0.1.6=py_0
  - yaml=0.2.5=h516909a_0
  - yarl=1.6.3=py38h25fe258_0
  - zipp=3.4.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - argon2-cffi==20.1.0
    - async-generator==1.10
    - backcall==0.2.0
    - bleach==3.3.0
    - dataclasses==0.6
    - decorator==4.4.2
    - defusedxml==0.6.0
    - deprecated==1.2.12
    - dill==0.3.3
    - easydict==1.9
    - entrypoints==0.3
    - facenet-pytorch==2.5.1
    - h3ds==0.1.1
    - imageio-ffmpeg==0.4.3
    - insightface==0.1.5
    - iopath==0.1.2
    - ipykernel==5.5.0
    - ipython==7.21.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.3
    - jedi==0.18.0
    - jinja2==2.11.3
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.11
    - jupyter-console==6.2.0
    - jupyter-core==4.7.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.0
    - lpips==0.1.3
    - markupsafe==1.1.1
    - mistune==0.8.4
    - mxnet==1.8.0
    - mxnet-cu110==1.8.0.post0
    - nbclient==0.5.3
    - nbconvert==6.0.7
    - nbformat==5.1.2
    - nest-asyncio==1.5.1
    - networkx==2.5
    - notebook==6.2.0
    - nvidia-htop==1.0.2
    - onnx==1.9.0
    - opencv-python==4.5.1.48
    - pandas==1.2.4
    - pandocfilters==1.4.3
    - parso==0.8.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - plotly==5.0.0
    - prometheus-client==0.9.0
    - prompt-toolkit==3.0.16
    - ptyprocess==0.7.0
    - pygments==2.8.0
    - pyqt5==5.15.4
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.8.1
    - pyrsistent==0.17.3
    - pytorch-fid==0.2.0
    - pytorch-lightning==1.1.8
    - pytorch-lightning-bolts==0.3.0
    - pywavelets==1.1.1
    - pyzmq==22.0.3
    - qdarkgraystyle==1.0.2
    - qdarkstyle==3.0.1
    - qtconsole==5.0.2
    - qtpy==1.9.0
    - scikit-image==0.18.1
    - scikit-learn==0.24.1
    - scipy==1.6.1
    - send2trash==1.5.0
    - tenacity==7.0.0
    - tensorboardx==2.1
    - terminado==0.9.2
    - testpath==0.4.4
    - threadpoolctl==2.1.0
    - tifffile==2021.2.1
    - toml==0.10.2
    - traitlets==5.0.5
    - trimesh==3.9.0
    - wandb==0.12.2
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
    - wrapt==1.12.1
